apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multiprompt-sandbox

bases:
  - ../../base

namePrefix: prod-

patchesStrategicMerge:
  - replica-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - environment=production
